<?php

namespace App\Http\Controllers\Ortu;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Student;
use Endroid\QrCode\Encoding\Encoding;
use Endroid\QrCode\Writer\PngWriter;
use Illuminate\Support\Facades\Response;

class BarcodeController extends Controller
{
    /**
     * Display barcode information and download option
     */
    public function index()
    {
        // Get the authenticated parent user
        $user = auth()->user();
        
        // Get the student associated with this parent
        $student = $user->students()->first();
        
        if (!$student) {
            return redirect()->route('ortu.dashboard')
                ->with('error', 'Anda belum terhubung dengan data siswa.');
        }
        
        return view('ortu.barcode.index', compact('student'));
    }

    /**
     * Download QR code for student (only for parent's own child)
     * Uses the same barcode that was generated by admin
     */
    public function download($id)
    {
        // Get the authenticated parent user
        $user = auth()->user();
        
        // Verify that the student belongs to this parent
        $student = $user->students()->where('id', $id)->firstOrFail();
        
        // Check if barcode exists in student record
        if (!$student->barcode) {
            return redirect()->route('ortu.dashboard')
                ->with('error', 'Barcode belum digenerate oleh admin. Silakan hubungi admin.');
        }
        
        // Data to encode in QR code - use only barcode value (same as admin)
        $data = $student->barcode;
        
        // Generate QR code using endroid/qr-code
        $writer = new PngWriter();
        $qrCode = new \Endroid\QrCode\QrCode(
            data: $data,
            encoding: new Encoding('UTF-8'),
            errorCorrectionLevel: \Endroid\QrCode\ErrorCorrectionLevel::High,
            size: 400,
            margin: 10,
            roundBlockSizeMode: \Endroid\QrCode\RoundBlockSizeMode::Margin,
            foregroundColor: new \Endroid\QrCode\Color\Color(0, 0, 0),
            backgroundColor: new \Endroid\QrCode\Color\Color(255, 255, 255)
        );
        
        $result = $writer->write($qrCode);
        
        // Get the PNG image data
        $qrCode = $result->getString();
        
        return Response::make($qrCode, 200, [
            'Content-Type' => 'image/png',
            'Content-Disposition' => 'attachment; filename="barcode-' . $student->nis . '.png"'
        ]);
    }

    /**
     * Print barcode for student
     */
    public function print($id)
    {
        // Get the authenticated parent user
        $user = auth()->user();
        
        // Verify that the student belongs to this parent
        $student = $user->students()->where('id', $id)->with('classSchedule')->firstOrFail();
        
        return view('ortu.barcode.print', compact('student'));
    }
}
